 name: Java CI with Gradle

 on:
   push:
     branches: [ "master" ]

 jobs:
   build:

     runs-on: self-hosted
     permissions:
       contents: read

     steps:
     # Step 1: Check out the repository
     - uses: actions/checkout@v4
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
         java-version: '17'
         distribution: 'temurin'

     # Step 2: Set up JDK 17
     - name: Setup Gradle
       uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
       
     # Step 3: Build the project using the Gradle Wrapper
     - name: Build with Gradle Wrapper
       run: ./gradlew build -x test

     # Step 4: Run the Spring Boot application in the background
     - name: Run the application in the background
       run: nohup java -jar build/libs/upskillenglish-0.0.1-SNAPSHOT.jar &
